# ArchDandara documentation
# Purpose: Defines AP location names and regions for the Dandara world.
# Why: Location names must match mod location ids and display text so checks resolve consistently.
# Notes: Display names here must match spoiler/log expectations because players use them for routing and bug reports.

# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

overworld_chest = [
	["Temple of Creation (17 Chest)", "Village of Artists"],
	["Temple of Creation (18 Chest)", "Village of Artists"],
	["Temple of Creation (3 NPC)", "Village of Artists"],
	["The Village Center (1 Chest)", "Village of Artists"],
	["Missile Alter", "Village of Artists"],
	["Buritis (13 Chest)", "Village of Artists"],
	["Dona Clara's Restaurant (14 Chest)", "Village of Artists"],
	["Beautiful Horizon Avenue (11 Chest)", "Village of Artists"],
	["Thommaz's House (2 NPC)", "Village of Artists"],
	["Garantido's Bar (12 Chest)", "Village of Artists"],
	["Lazúli's House (15 Chest)", "Village of Artists"],
	["Lazúli's House (16 Chest)", "Village of Artists"],
	["Tarsila's House (1 NPC)", "Village of Artists"],
	["Tarsila's House (10 Chest)", "Village of Artists"],
	["Paint Well (8 Chest)", "Village of Artists"],
	["Community Street (9 Chest)", "Village of Artists"],
	["Foyer of Formidable Burdens (29 Chest)", "Remembrance Desert"],
	["Foyer of Formidable Burdens (30 Chest)", "Remembrance Desert"],
	["Archive of the Child (32 Chest)", "Remembrance Desert"],
	["Overcast Gate Ruins (33 Chest)", "Remembrance Desert"],
	["Overcast Gate Ruins (34 Chest)", "Remembrance Desert"],
	["Overcast Gate Ruins (35 Chest)", "Remembrance Desert"],
	["Overcast Gate Ruins (NPC 4)", "Remembrance Desert"],
	["Broken Heart Archive (31 Chest)", "Remembrance Desert"],
	["Main Warehouse (23 Chest)", "Remembrance Desert"],
	["Main Warehouse (24 Chest)", "Remembrance Desert"],
	["Main Warehouse (25 Chest)", "Remembrance Desert"],
	["The Treasure (28 Chest)", "Remembrance Desert"],
	["Remembrance Cliff (2 Altar)", "Remembrance Desert"],
	["Quarter of a Distant Love (3 Altar)", "Remembrance Desert"],
	["Auditorium (26 Chest)", "Remembrance Desert"],
	["Overburden Deposits (27 Chest)", "Remembrance Desert"],
	["Museum Main Hall (22 Chest)", "Remembrance Desert"],
	["Parlance Road (45 Chest)", "Intention Capital"],
	["Eagle Highway (61 Chest)", "Intention Capital"],
	["Side Turn (37 Chest)", "Intention Capital"],
	["Side Turn (38 Chest)", "Intention Capital"],
	["The Perfect Corner (6 Altar)", "Intention Capital"],
	["Reasoning Lock (44 Chest)", "Intention Capital"],
	["Crib of Intention (4 Altar)", "Intention Capital"],
	["Back Alley (39 Chest)", "Intention Capital"],
	["Back Alley (40 Chest)", "Intention Capital"],
	["Recycle Room (41 Chest)", "Intention Capital"],
	["Corner's Club (52 Chest)", "Dream Lands"],
	["Shock Alter", "Dream Lands"],
	["Dream Lands (53 Chest)", "Dream Lands"],
	["Dream Lands (55 Chest)", "Dream Lands"],
	["Dream Lands (56 Chest)", "Dream Lands"],
	["Dream Lands (57 Chest)", "Dream Lands"],
	["Dream Lands (58 Chest)", "Dream Lands"],
	["Dream Lands (59 Chest)", "Dream Lands"],
	["Dream Lands (60 Chest)", "Dream Lands"],
	["Dream Lands (5 Altar)", "Dream Lands"],
	["Limits of Sanity (19 Chest)", "Primal Woods"],
	["Cave of Desire (51 Chest)", "Primal Woods"],
	["Confusion Ruins (6 Chest)", "Primal Woods"],
	["Confusion Ruins (7 Chest)", "Primal Woods"],
	["Structural Cave (36 Chest)", "Intention Capital"],
	["Palmares Track (2 Chest)", "Crib of Creation"],
	["Pleasure Woods (3 Chest)", "Crib of Creation"],
	["Pleasure Woods (4 Chest)", "Crib of Creation"],
	["Pleasure Woods (5 Chest)", "Crib of Creation"],
	["Wealth Lair (21 Chest)", "The Colossal Bridge"],
	["The Golden Corner (66 Chest)", "Intention Capital"],
	["The Golden Angle (42 Chest)", "Intention Capital"],
	["The Golden Angle (43 Chest)", "Intention Capital"],
	["The Golden Storage (46 Chest)", "Intention Capital"],
	["The Golden Storage (47 Chest)", "Intention Capital"],
	["The Golden Storage (48 Chest)", "Intention Capital"],
	["The Golden Storage (49 Chest)", "Intention Capital"],
	["A Good Bargain (70 Chest)", "Intention Capital"],
	["Kill Eldar", "Golden Fortress"],
	["No Pain, No Gain (62 Chest)", "Golden Fortress"],
	["Command Center (63 Chest)", "Golden Fortress"],
	["Greediness Space (64 Chest)", "Golden Fortress"],
	["Greediness Space (65 Chest)", "Golden Fortress"],
	["Miserliness Space (67 Chest)", "Golden Fortress"],
	["Miserliness Space (68 Chest)", "Golden Fortress"],
	["Miserliness Space (69 Chest)", "Golden Fortress"],
	["Eldarian Gates (20 Chest)", "Golden Fortress"]
]

fearworld_chest = [
	["Crumbling Hollow (1 Chest)", "Hidden Realms"],
	["Incident Square (10 Chest)", "Hidden Realms"],
	["Station Rendezvous (11 Chest)", "Ephemeral Station"],
	["Station Rendezvous (12 Chest)", "Ephemeral Station"],
	["Pusher's Assignment (13 Chest)", "Ephemeral Station"],
	["Waiter's Room (14 Chest)", "Ephemeral Station"],
	["Through The Eyes of Fear (15 Chest)", "Hidden Realms"],
	["Hidden Eye (16 Chest)", "Hidden Realms"],
	["Alchemist's Gallery (17 Chest)", "The Privileged Keep"],
	["Underlying Truth (18 Chest)", "Hidden Realms"],
	["True Explorers Treasure (19 Chest)", "Hidden Realms"],
	["A Dark Angle (2 Chest)", "Hidden Realms"],
	["Friendly Gathering (20 Chest)", "The Masquerade Ball"],
	["Friendly Gathering (21 Chest)", "The Masquerade Ball"],
	["Ostentation Room (22 Chest)", "The Masquerade Ball"],
	["Weak-Minded Segregation (23 Chest)", "The Masquerade Ball"],
	["Secrets Beneath Masks (24 Chest)", "The Masquerade Ball"],
	["Finite Run (3 Chest)", "Hidden Realms"],
	["Students Way (4 Chest)", "Hidden Realms"],
	["Pain Sanctuary (5 Chest)", "The Enduring Fortress"],
	["Wrecked Nakaturen Bridge (6 Chest)", "The Pioneer Facility"],
	["Nevermore a Beautiful Horizon (7 Chest)", "Hidden Realms"],
	["Auditorium Hall (8 Chest)", "Masters' Auditorium"],
	["Windy Hall (9 Chest)", "Hidden Realms"],
	["Resilience Growth (3 Altar)", "Hidden Realms"],
	["Future Path Gate (2 Altar)", "Ephemeral Station"],
	["The Grand Stage (1 Altar)", "Masters' Auditorium"],
	["The Grand Stage (NPC 1)", "Masters' Auditorium"],
	["The Grand Stage (NPC 2)", "Masters' Auditorium"],
	["The Grand Stage (NPC 3)", "Masters' Auditorium"],
	["The Grand Stage (NPC 4)", "Masters' Auditorium"],
	["Nakaturen Frigate Elevator (NPC 5)", "The Pioneer Facility"],
	["Castle Entrance (NPC 6)", "The Privileged Keep"],
	["Rock Cave (NPC 7)", "The Enduring Fortress"],
	["Wrecked Nakaturen Bridge (NPC 8)", "The Pioneer Facility"],
	["Pain Sanctuary (NPC 9)", "The Enduring Fortress"],
	["Rest of the Acolyte (NPC 10)", "The Privileged Keep"],
	["Rock Cave (NPC 11)", "The Enduring Fortress"],
	["Nara's Cage (NPC 12)", "Exile of Contemplations"]
]

shop_levels = [
	["Buy Upgrade 1", "Crib of Creation"],
	["Buy Upgrade 2", "Village of Artists"],
	["Buy Upgrade 3", "The Colossal Bridge"],
	["Buy Upgrade 4", "The Colossal Bridge"],
	["Buy Upgrade 5", "The Colossal Bridge"],
	["Buy Upgrade 6", "Remembrance Desert"],
	["Buy Upgrade 7", "Remembrance Desert"],
	["Buy Upgrade 8", "Remembrance Desert"],
	["Buy Upgrade 9", "Remembrance Desert"],
	["Buy Upgrade 10", "Hidden Realms"],
	["Buy Upgrade 11", "Hidden Realms"],
	["Buy Upgrade 12", "Hidden Realms"],
	["Buy Upgrade 13", "Hidden Realms"],
	["Buy Upgrade 14", "Intention Capital"],
	["Buy Upgrade 15", "Masters' Auditorium"],
	["Buy Upgrade 16", "Dream Lands"],
	["Buy Upgrade 17", "Ephemeral Station"],
	["Buy Upgrade 18", "Ephemeral Station"],
	["Buy Upgrade 19", "Ephemeral Station"],
	["Buy Upgrade 20", "Ephemeral Station"],
	["Buy Upgrade 21", "Ephemeral Station"],
	["Buy Upgrade 22", "Ephemeral Station"],
	["Buy Upgrade 23", "Ephemeral Station"],
	["Buy Upgrade 24", "Ephemeral Station"],
	["Buy Upgrade 25", "Ephemeral Station"],
	["Buy Upgrade 26", "Ephemeral Station"],
	["Buy Upgrade 27", "Ephemeral Station"],
	["Buy Upgrade 28", "Ephemeral Station"],
	["Buy Upgrade 29", "Ephemeral Station"],
	["Buy Upgrade 30", "Golden Fortress"],
	["Buy Upgrade 31", "Golden Fortress"],
	["Buy Upgrade 32", "Golden Fortress"],
	["Buy Upgrade 33", "The Masquerade Ball"],
	["Buy Upgrade 34", "The Masquerade Ball"],
	["Buy Upgrade 35", "The Masquerade Ball"],
	["Buy Upgrade 36", "Exile of Contemplations"],
	["Buy Upgrade 37", "Exile of Contemplations"],
	["Buy Upgrade 38", "Exile of Contemplations"],
	["Buy Upgrade 39", "Exile of Contemplations"],
	["Buy Upgrade 40", "Exile of Contemplations"],
	["Buy Upgrade 41", "Exile of Contemplations"],
	["Buy Upgrade 42", "Exile of Contemplations"],
	["Buy Upgrade 43", "Exile of Contemplations"],
	["Buy Upgrade 44", "Exile of Contemplations"]
]

boss_locations = [
	["Kill Boss 1", "Village of Artists"],
	["Kill Boss 2", "Remembrance Desert"]
]

location_dict = [
	*[items[0] for items in overworld_chest],
	*[items[0] for items in fearworld_chest],
	*[items[0] for items in shop_levels],
	*[items[0] for items in boss_locations]
]
