# ArchDandara documentation
# Purpose: Applies item requirements to AP locations and helper logic groups.
# Why: This prevents AP from placing progression behind checks the player cannot logically reach.
# Notes: Helper functions should be reused for common movement requirements so logic changes stay consistent.

import math
from .Locations import *

# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

def get_rule_map(player, options):
	return {
		"Temple of Creation (17 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Displaced Presence") and has(state, player, options, "Boss StoryEvent Key 1")) or (has_blast(state, player, options) and has(state, player, options, "Stone of Creation") and has(state, player, options, "Music Platform") and has(state, player, options, "Boss StoryEvent Key 1")) or (has_blast(state, player, options) and has(state, player, options, "Stone of Creation") and has(state, player, options, "Boss StoryEvent Key 1")) or (has_blast(state, player, options) and has(state, player, options, "Paint Platform") and has(state, player, options, "Boss StoryEvent Key 1")),
		"Temple of Creation (18 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Displaced Presence") and has(state, player, options, "Boss StoryEvent Key 1")) or (has_blast(state, player, options) and has(state, player, options, "Stone of Creation") and has(state, player, options, "Music Platform") and has(state, player, options, "Boss StoryEvent Key 1")) or (has_blast(state, player, options) and has(state, player, options, "Stone of Creation") and has(state, player, options, "Boss StoryEvent Key 1")) or (has_blast(state, player, options) and has(state, player, options, "Paint Platform") and has(state, player, options, "Boss StoryEvent Key 1")),
		"Kill Boss 1": lambda state: (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")) or (has_blast(state, player, options) and has(state, player, options, "Stone of Creation") and has(state, player, options, "Music Platform")) or (has_blast(state, player, options) and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "Paint Platform")),
		"Temple of Creation (3 NPC)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")) or (has_blast(state, player, options) and has(state, player, options, "Stone of Creation") and has(state, player, options, "Music Platform")) or (has_blast(state, player, options) and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "Paint Platform")),
		"The Village Center (1 Chest)": lambda state: has(state, player, options, "Paint Platform") or has(state, player, options, "Displaced Presence") or (has_blast(state, player, options) and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Stone of Creation") and has(state, player, options, "Music Platform")),
		"Missile Alter": lambda state: (has(state, player, options, "Paint Platform") and has(state, player, options, "Music Platform")) or (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Displaced Presence") and has(state, player, options, "Music Platform")),
		"Buritis (13 Chest)": lambda state: (has(state, player, options, "Paint Platform") and has(state, player, options, "Music Platform")) or (has(state, player, options, "Displaced Presence") and has(state, player, options, "Jonny B. Missiles")),
		"Dona Clara's Restaurant (14 Chest)": lambda state: has(state, player, options, "Jonny B. Missiles") and has(state, player, options, "Displaced Presence"),
		"Beautiful Horizon Avenue (11 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")) or (has_blast(state, player, options) and has(state, player, options, "Paint Platform")) or (has_blast(state, player, options) and has(state, player, options, "Paint Platform") and has(state, player, options, "Music Platform")) or (has_blast(state, player, options) and has(state, player, options, "Stone of Creation")),
		"Thommaz's House (2 NPC)": lambda state: has(state, player, options, "Stone of Creation") or has(state, player, options, "Paint Platform") or has(state, player, options, "Displaced Presence"),
		"Garantido's Bar (12 Chest)": lambda state: (has(state, player, options, "Paint Platform") and has(state, player, options, "Music Platform")) or (has(state, player, options, "Displaced Presence") and has(state, player, options, "Music Platform")) or has(state, player, options, "Stone of Creation") or (has_blast(state, player, options) and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Stone of Creation") and has(state, player, options, "Music Platform")),
		"Lazúli's House (15 Chest)": lambda state: (has(state, player, options, "Paint Platform") and has(state, player, options, "Music Platform")) or has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence"),
		"Lazúli's House (16 Chest)": lambda state: (has(state, player, options, "Paint Platform") and has(state, player, options, "Music Platform")) or has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence"),
		"Tarsila's House (10 Chest)": lambda state: has(state, player, options, "Paint Platform") or (has_reach(state, player, options) and has(state, player, options, "Displaced Presence")),
		"Foyer of Formidable Burdens (29 Chest)": lambda state: has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence"),
		"Foyer of Formidable Burdens (30 Chest)": lambda state: has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence"),
		"Archive of the Child (32 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")),
		"Overcast Gate Ruins (33 Chest)": lambda state: (has(state, player, options, "Boss StoryEvent Key 2") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Boss StoryEvent Key 2") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")),
		"Overcast Gate Ruins (34 Chest)": lambda state: (has(state, player, options, "Boss StoryEvent Key 2") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Boss StoryEvent Key 2") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")),
		"Overcast Gate Ruins (35 Chest)": lambda state: (has(state, player, options, "Boss StoryEvent Key 2") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Boss StoryEvent Key 2") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")),
		"Overcast Gate Ruins (NPC 4)": lambda state: (has(state, player, options, "Boss StoryEvent Key 2") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Boss StoryEvent Key 2") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")),
		"Broken Heart Archive (31 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")),
		"Main Warehouse (23 Chest)": lambda state: has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence"),
		"Main Warehouse (24 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")),
		"Main Warehouse (25 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")),
		"The Treasure (28 Chest)": lambda state: (has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance")) or (has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance")),
		"Remembrance Cliff (2 Altar)": lambda state: has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence"),
		"Quarter of a Distant Love (3 Altar)": lambda state: (has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")),
		"Auditorium (26 Chest)": lambda state: has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence"),
		"Overburden Deposits (27 Chest)": lambda state: (has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Displaced Presence")),
		"Museum Main Hall (22 Chest)": lambda state: (has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance")) or (has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance")),
		"Parlance Road (45 Chest)": lambda state: (has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or has(state, player, options, "Displaced Presence"),
		"Eagle Highway (61 Chest)": lambda state: has(state, player, options, "Displaced Presence") or (has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")),
		"Side Turn (37 Chest)": lambda state: (has(state, player, options, "Stone of Intention") and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")),
		"Side Turn (38 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Stone of Intention") and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")),
		"The Perfect Corner (6 Altar)": lambda state: has(state, player, options, "Displaced Presence") or (has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")),
		"Reasoning Lock (44 Chest)": lambda state: has(state, player, options, "Displaced Presence") or (has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance")) or (has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"Crib of Intention (4 Altar)": lambda state: has(state, player, options, "Displaced Presence") or (has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance")) or (has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"Back Alley (39 Chest)": lambda state: has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence"),
		"Back Alley (40 Chest)": lambda state: has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence"),
		"Recycle Room (41 Chest)": lambda state: has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence"),
		"A Good Bargain (70 Chest)": lambda state: has_blast(state, player, options) and (has(state, player, options, "Displaced Presence") or has(state, player, options, "Stone of Intention")),
		"Corner's Club (52 Chest)": lambda state: (has(state, player, options, "Stone of Intention") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Stone of Intention") and has(state, player, options, "Stone of Creation")),
		"Shock Alter": lambda state: (has(state, player, options, "Stone of Intention") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Stone of Intention") and has(state, player, options, "Stone of Creation")),
		"Dream Lands (53 Chest)": lambda state: (has(state, player, options, "Stone of Intention") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Stone of Intention") and has(state, player, options, "Stone of Creation")),
		"Dream Lands (55 Chest)": lambda state: (has(state, player, options, "Stone of Intention") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Stone of Intention") and has(state, player, options, "Stone of Creation")),
		"Dream Lands (56 Chest)": lambda state: (has(state, player, options, "Stone of Intention") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Stone of Intention") and has(state, player, options, "Stone of Creation")),
		"Dream Lands (57 Chest)": lambda state: (has(state, player, options, "Stone of Intention") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Stone of Intention") and has(state, player, options, "Stone of Creation")),
		"Dream Lands (58 Chest)": lambda state: (has(state, player, options, "Stone of Intention") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Stone of Intention") and has(state, player, options, "Stone of Creation")),
		"Dream Lands (59 Chest)": lambda state: (has(state, player, options, "Stone of Intention") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Stone of Intention") and has(state, player, options, "Stone of Creation")),
		"Dream Lands (60 Chest)": lambda state: (has(state, player, options, "Stone of Intention") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Stone of Intention") and has(state, player, options, "Stone of Creation")),
		"Dream Lands (5 Altar)": lambda state: (has(state, player, options, "Stone of Intention") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Stone of Intention") and has(state, player, options, "Stone of Creation")),
		"Limits of Sanity (19 Chest)": lambda state: (has(state, player, options, "Stone of Intention") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Stone of Intention") and has(state, player, options, "Displaced Presence")),
		"Cave of Desire (51 Chest)": lambda state: (has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance")) or (has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance")) or (has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")),
		"Confusion Ruins (7 Chest)": lambda state: has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence"),
		"Structural Cave (36 Chest)": lambda state: has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence"),
		"Palmares Track (2 Chest)": lambda state: has_blast(state, player, options),
		"Pleasure Woods (3 Chest)": lambda state: has_blast(state, player, options) and has(state, player, options, "Rock of Remembrance"),
		"Pleasure Woods (4 Chest)": lambda state: has_blast(state, player, options) and has(state, player, options, "Rock of Remembrance"),
		"Pleasure Woods (5 Chest)": lambda state: has_blast(state, player, options) and has(state, player, options, "Rock of Remembrance"),
		"Wealth Lair (21 Chest)": lambda state: has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence"),
		"The Golden Corner (66 Chest)": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")),
		"The Golden Angle (42 Chest)": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"The Golden Angle (43 Chest)": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"The Golden Storage (46 Chest)": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"The Golden Storage (47 Chest)": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"The Golden Storage (48 Chest)": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"The Golden Storage (49 Chest)": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"Kill Eldar": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")),
		"No Pain, No Gain (62 Chest)": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"Command Center (63 Chest)": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"Greediness Space (64 Chest)": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"Greediness Space (65 Chest)": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"Miserliness Space (67 Chest)": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"Miserliness Space (68 Chest)": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"Miserliness Space (69 Chest)": lambda state: (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Wall Break") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention")),
		"Eldarian Gates (20 Chest)": lambda state: has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence"),
		"Incident Square (10 Chest)": lambda state: (has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence")),
		"Station Rendezvous (11 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has_blast(state, player, options) and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")),
		"Station Rendezvous (12 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has_blast(state, player, options) and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")),
		"Pusher's Assignment (13 Chest)": lambda state: (has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")),
		"Waiter's Room (14 Chest)": lambda state: (has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")),
		"Through The Eyes of Fear (15 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Shell Mirror") and has(state, player, options, "Skin Knitter") and has(state, player, options, "Paint Platform") and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "Shell Mirror") and has(state, player, options, "Skin Knitter") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "Shell Mirror") and has(state, player, options, "Skin Knitter") and has(state, player, options, "Stone of Creation")),
		"Hidden Eye (16 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Skin Knitter") and has(state, player, options, "Displaced Presence")) or (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")),
		"Alchemist's Gallery (17 Chest)": lambda state: (has(state, player, options, "DLC StoryEvent 1") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "DLC StoryEvent 1") and has(state, player, options, "Displaced Presence")),
		"Underlying Truth (18 Chest)": lambda state: (has_weapon_duo(state, player, options) and has(state, player, options, "Stone of Creation")) or (has_weapon_duo(state, player, options) and has(state, player, options, "Displaced Presence")),
		"True Explorers Treasure (19 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Stone of Creation") and has(state, player, options, "Skin Knitter")) or (has_blast(state, player, options) and has(state, player, options, "Displaced Presence") and has(state, player, options, "Skin Knitter")) or (has(state, player, options, "Stone of Creation") and has(state, player, options, "Skin Knitter")) or (has(state, player, options, "Displaced Presence") and has(state, player, options, "Skin Knitter")),
		"A Dark Angle (2 Chest)": lambda state: (has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance")) or (has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance")),
		"Friendly Gathering (20 Chest)": lambda state: has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention"),
		"Friendly Gathering (21 Chest)": lambda state: has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention"),
		"Ostentation Room (22 Chest)": lambda state: has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention"),
		"Weak-Minded Segregation (23 Chest)": lambda state: has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention"),
		"Secrets Beneath Masks (24 Chest)": lambda state: has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention"),
		"Finite Run (3 Chest)": lambda state: has(state, player, options, "Displaced Presence") or has(state, player, options, "Skin Knitter"),
		"Students Way (4 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")),
		"Pain Sanctuary (5 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "DLC StoryEvent 1") and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "DLC StoryEvent 1") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "DLC StoryEvent 1") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Skin Knitter")) or (has(state, player, options, "DLC StoryEvent 1") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "DLC StoryEvent 1") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Skin Knitter") and has(state, player, options, "Rock of Remembrance")) or (has(state, player, options, "DLC StoryEvent 1") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance")),
		"Wrecked Nakaturen Bridge (6 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "DLC StoryEvent 1") and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "DLC StoryEvent 1") and has(state, player, options, "Displaced Presence")),
		"Nevermore a Beautiful Horizon (7 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "Paint Platform")) or (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")),
		"Auditorium Hall (8 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Displaced Presence") and has(state, player, options, "Skin Knitter")) or (has(state, player, options, "Displaced Presence") and has(state, player, options, "Rock of Remembrance")) or (has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance")),
		"Windy Hall (9 Chest)": lambda state: (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Displaced Presence") and has(state, player, options, "Skin Knitter")) or (has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance")),
		"Future Path Gate (2 Altar)": lambda state: (has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Creation") and has(state, player, options, "Stone of Intention")) or (has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Displaced Presence") and has(state, player, options, "Stone of Intention")),
		"The Grand Stage (1 Altar)": lambda state: (has(state, player, options, "DLC StoryEvent 1") and has(state, player, options, "DLC StoryEvent 5") and has(state, player, options, "DLC StoryEvent 6") and has(state, player, options, "DLC StoryEvent 7") and has(state, player, options, "Stone of Creation")) or (has(state, player, options, "DLC StoryEvent 1") and has(state, player, options, "DLC StoryEvent 5") and has(state, player, options, "DLC StoryEvent 6") and has(state, player, options, "DLC StoryEvent 7") and has(state, player, options, "Displaced Presence")),
		"The Grand Stage (NPC 1)": lambda state: True,
		"The Grand Stage (NPC 2)": lambda state: True,
		"The Grand Stage (NPC 3)": lambda state: True,
		"The Grand Stage (NPC 4)": lambda state: (has(state, player, options, "Skin Knitter") and has(state, player, options, "Displaced Presence")) or has(state, player, options, "Stone of Creation") or has(state, player, options, "Displaced Presence") or (has_blast(state, player, options) and has(state, player, options, "Stone of Creation")) or (has_blast(state, player, options) and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "Skin Knitter") and has(state, player, options, "Stone of Creation")),
		"Nakaturen Frigate Elevator (NPC 5)": lambda state: has(state, player, options, "DLC StoryEvent 2"),
		"Castle Entrance (NPC 6)": lambda state: has(state, player, options, "DLC StoryEvent 3"),
		"Rock Cave (NPC 7)": lambda state: has(state, player, options, "DLC StoryEvent 4"),
		"Wrecked Nakaturen Bridge (NPC 8)": lambda state: has(state, player, options, "DLC StoryEvent 5") and has(state, player, options, "TimeFlag"),
		"Pain Sanctuary (NPC 9)": lambda state: (has(state, player, options, "TimeFlag") and has(state, player, options, "Displaced Presence")) or (has(state, player, options, "TimeFlag") and has(state, player, options, "Stone of Creation")),
		"Rest of the Acolyte (NPC 10)": lambda state: has(state, player, options, "DLC StoryEvent 6"),
		"Rock Cave (NPC 11)": lambda state: has(state, player, options, "DLC StoryEvent 7"),
		"Nara's Cage (NPC 12)": lambda state: has(state, player, options, "Shell Mirror"),
		"Event: Kill Eldar": lambda state: (has(state, player, options, "Stone of Creation") and has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Pearl of Dreams")) or (has(state, player, options, "Rock of Remembrance") and has(state, player, options, "Stone of Intention") and has(state, player, options, "Pearl of Dreams") and has(state, player, options, "Displaced Presence")),
		"Event: Ture Ending": lambda state: has(state, player, options, "FinalBoss_Kill") and has(state, player, options, "FreeNara"),
		"Buy Upgrade 1": lambda state: can_reach_shop_level(state, player, options, 1),
		"Buy Upgrade 2": lambda state: can_reach_shop_level(state, player, options, 2),
		"Buy Upgrade 3": lambda state: can_reach_shop_level(state, player, options, 3),
		"Buy Upgrade 4": lambda state: can_reach_shop_level(state, player, options, 4),
		"Buy Upgrade 5": lambda state: can_reach_shop_level(state, player, options, 5),
		"Buy Upgrade 6": lambda state: can_reach_shop_level(state, player, options, 6),
		"Buy Upgrade 7": lambda state: can_reach_shop_level(state, player, options, 7),
		"Buy Upgrade 8": lambda state: can_reach_shop_level(state, player, options, 8),
		"Buy Upgrade 9": lambda state: can_reach_shop_level(state, player, options, 9),
		"Buy Upgrade 10": lambda state: can_reach_shop_level(state, player, options, 10),
		"Buy Upgrade 11": lambda state: can_reach_shop_level(state, player, options, 11),
		"Buy Upgrade 12": lambda state: can_reach_shop_level(state, player, options, 12),
		"Buy Upgrade 13": lambda state: can_reach_shop_level(state, player, options, 13),
		"Buy Upgrade 14": lambda state: can_reach_shop_level(state, player, options, 14),
		"Buy Upgrade 15": lambda state: can_reach_shop_level(state, player, options, 15),
		"Buy Upgrade 16": lambda state: can_reach_shop_level(state, player, options, 16),
		"Buy Upgrade 17": lambda state: can_reach_shop_level(state, player, options, 17),
		"Buy Upgrade 18": lambda state: can_reach_shop_level(state, player, options, 18),
		"Buy Upgrade 19": lambda state: can_reach_shop_level(state, player, options, 19),
		"Buy Upgrade 20": lambda state: can_reach_shop_level(state, player, options, 20),
		"Buy Upgrade 21": lambda state: can_reach_shop_level(state, player, options, 21),
		"Buy Upgrade 22": lambda state: can_reach_shop_level(state, player, options, 22),
		"Buy Upgrade 23": lambda state: can_reach_shop_level(state, player, options, 23),
		"Buy Upgrade 24": lambda state: can_reach_shop_level(state, player, options, 24),
		"Buy Upgrade 25": lambda state: can_reach_shop_level(state, player, options, 25),
		"Buy Upgrade 26": lambda state: can_reach_shop_level(state, player, options, 26),
		"Buy Upgrade 27": lambda state: can_reach_shop_level(state, player, options, 27),
		"Buy Upgrade 28": lambda state: can_reach_shop_level(state, player, options, 28),
		"Buy Upgrade 29": lambda state: can_reach_shop_level(state, player, options, 29),
		"Buy Upgrade 30": lambda state: can_reach_shop_level(state, player, options, 30),
		"Buy Upgrade 31": lambda state: can_reach_shop_level(state, player, options, 31),
		"Buy Upgrade 32": lambda state: can_reach_shop_level(state, player, options, 32),
		"Buy Upgrade 33": lambda state: can_reach_shop_level(state, player, options, 33),
		"Buy Upgrade 34": lambda state: can_reach_shop_level(state, player, options, 34),
		"Buy Upgrade 35": lambda state: can_reach_shop_level(state, player, options, 35),
		"Buy Upgrade 36": lambda state: can_reach_shop_level(state, player, options, 36),
		"Buy Upgrade 37": lambda state: can_reach_shop_level(state, player, options, 37),
		"Buy Upgrade 38": lambda state: can_reach_shop_level(state, player, options, 38),
		"Buy Upgrade 39": lambda state: can_reach_shop_level(state, player, options, 39),
		"Buy Upgrade 40": lambda state: can_reach_shop_level(state, player, options, 40),
		"Buy Upgrade 41": lambda state: can_reach_shop_level(state, player, options, 41),
		"Buy Upgrade 42": lambda state: can_reach_shop_level(state, player, options, 42),
		"Buy Upgrade 43": lambda state: can_reach_shop_level(state, player, options, 43),
		"Buy Upgrade 44": lambda state: can_reach_shop_level(state, player, options, 44),
	}

def get_yaml_option(state, player, options, option) -> bool:
	return options.get_options_map(option).value

def has_amount(state, player, options, item, amount) -> bool:
	return state.has(item, player, amount)

def has(state, player, options, item) -> bool:
	return has_amount(state, player, options, item, 1)

def has_any(state, player, options, items) -> bool:
	return any(has(state, player, options, item) for item in items)

def has_all(state, player, options, items) -> bool:
	return all(has(state, player, options, item) for item in items)

def can_reach_shop_level(state, player, options, level) -> bool:
	sum = 0
	if state.has("Heart Enhancer Permit", player, 1):
		sum += 20
	if state.has("Freedom Enhancer Permit", player, 1):
		sum += 10
	if state.has("Essence Enhancer Permit", player, 1):
		sum += 7
	if state.has("Infusion Enhancer Permit", player, 1):
		sum += 7
	return sum >= level

def has_weapon_duo(state, player, options) -> bool:
	return state.has_from_list_unique(["Anxiety Shock", "Skin Knitter", "Memories Shaft"], player, 2)

def has_blast(state, player, options) -> bool:
	return has(state, player, options, "Jonny B. Missiles") or has(state, player, options, "Logic Blast")

def has_reach(state, player, options) -> bool:
	return has(state, player, options, "Jonny B. Missiles") or has(state, player, options, "Anxiety Shock") or has(state, player, options, "Logic Blast") or has(state, player, options, "Skin Knitter")
