-- APWorld name mappings. Keep the table keys exactly equal to the Archipelago item/location names.
AP_ITEM_MAP = {
    ["FearKey"] = "fear_key",
    ["FreeNara"] = "free_nara",
    ["TimeFlag"] = "time_flag",
    ["Boss StoryEvent Key 1"] = "boss_storyevent_key_1",
    ["Boss StoryEvent Key 2"] = "boss_storyevent_key_2",
    ["Stone of Creation"] = "stone_creation",
    ["Rock of Remembrance"] = "rock_remembrance",
    ["Stone of Intention"] = "stone_intention",
    ["Pearl of Dreams"] = "pearl_dreams",
    ["Shell Mirror"] = "shell_mirror",
    ["Heart of the Great Salt"] = "heart_great_salt",
    ["Scarf of Freedom"] = "scarf_freedom",
    ["Essence of Salt"] = "essence_salt",
    ["Infusion of Salt"] = "infusion_salt",
    ["Essence of Salt Enhancer"] = "essence_salt_enhancer",
    ["Infusion of Salt Enhancer"] = "infusion_salt_enhancer",
    ["Jonny B. Missiles"] = "jonny_b_missiles",
    ["Anxiety Shock"] = "anxiety_shock",
    ["Memories Shaft"] = "memories_shaft",
    ["Logic Blast"] = "logic_blast",
    ["Skin Knitter"] = "skin_knitter",
    ["Displaced Presence"] = "displaced_presence",
    ["Paint Platform"] = "paint_platform",
    ["Music Platform"] = "music_platform",
    ["Dandara Arrow Damage Upgrade"] = "dandara_arrow_damage_upgrade",
    ["Dandara Weapon Damage Upgrade"] = "dandara_weapon_damage_upgrade",
    ["Salt's Awareness Upgrade"] = "salts_awareness_upgrade",
    ["D_DLCF DLC StoryEvent 1"] = "dlc_storyevent_1",
    ["D_DLCF DLC StoryEvent 2"] = "dlc_storyevent_2",
    ["D_DLCF DLC StoryEvent 3"] = "dlc_storyevent_3",
    ["D_DLCF DLC StoryEvent 4"] = "dlc_storyevent_4",
    ["D_DLCF DLC StoryEvent 5"] = "dlc_storyevent_5",
    ["D_DLCF DLC StoryEvent 6"] = "dlc_storyevent_6",
    ["D_DLCF DLC StoryEvent 7"] = "dlc_storyevent_7",
    ["D_DLCF_DLC StoryEvent 1"] = "dlc_storyevent_1",
    ["D_DLCF_DLC StoryEvent 2"] = "dlc_storyevent_2",
    ["D_DLCF_DLC StoryEvent 3"] = "dlc_storyevent_3",
    ["D_DLCF_DLC StoryEvent 4"] = "dlc_storyevent_4",
    ["D_DLCF_DLC StoryEvent 5"] = "dlc_storyevent_5",
    ["D_DLCF_DLC StoryEvent 6"] = "dlc_storyevent_6",
    ["D_DLCF_DLC StoryEvent 7"] = "dlc_storyevent_7",
    ["DLC StoryEvent 1"] = "dlc_storyevent_1",
    ["DLC StoryEvent 2"] = "dlc_storyevent_2",
    ["DLC StoryEvent 3"] = "dlc_storyevent_3",
    ["DLC StoryEvent 4"] = "dlc_storyevent_4",
    ["DLC StoryEvent 5"] = "dlc_storyevent_5",
    ["DLC StoryEvent 6"] = "dlc_storyevent_6",
    ["DLC StoryEvent 7"] = "dlc_storyevent_7",
    ["Wall Break"] = "wall_break",
    ["Essence Enhancer Permit"] = "essence_enhancer_permit",
    ["Infusion Enhancer Permit"] = "infusion_enhancer_permit",
    ["Freedom Enhancer Permit"] = "freedom_enhancer_permit",
    ["Heart Enhancer Permit"] = "heart_enhancer_permit",
    ["Map"] = "map",
    ["Bracers of the Patient"] = "bracers_patient",
    ["Arrow of Freedom"] = "arrow_freedom",
    ["Salt's Awareness"] = "salts_awareness",
    ["Pleas of the Salt Fear"] = "pleas_salt_fear",
    ["Pleas of the Salt"] = "pleas_salt",
    ["Salt"] = "salt",
}

-- APWorld item IDs from item_name_to_id. Used as a fallback when AP sends an item name that does not match the numeric ID.
AP_ITEM_ID_MAP = {
    [1] = "fear_key", -- FearKey
    [2] = "time_flag", -- TimeFlag
    [3] = "boss_storyevent_key_1", -- Boss StoryEvent Key 1
    [4] = "boss_storyevent_key_2", -- Boss StoryEvent Key 2
    [5] = "shell_mirror", -- Shell Mirror
    [6] = "heart_great_salt", -- Heart of the Great Salt
    [7] = "scarf_freedom", -- Scarf of Freedom
    [8] = "essence_salt", -- Essence of Salt
    [9] = "infusion_salt", -- Infusion of Salt
    [10] = "essence_salt_enhancer", -- Essence of Salt Enhancer
    [11] = "infusion_salt_enhancer", -- Infusion of Salt Enhancer
    [12] = "displaced_presence", -- Displaced Presence
    [13] = "dlc_storyevent_1", -- DLC StoryEvent 1
    [14] = "dlc_storyevent_2", -- DLC StoryEvent 2
    [15] = "dlc_storyevent_3", -- DLC StoryEvent 3
    [16] = "dlc_storyevent_4", -- DLC StoryEvent 4
    [17] = "dlc_storyevent_5", -- DLC StoryEvent 5
    [18] = "dlc_storyevent_6", -- DLC StoryEvent 6
    [19] = "dlc_storyevent_7", -- DLC StoryEvent 7
    [20] = "wall_break", -- Wall Break
    [21] = "essence_enhancer_permit", -- Essence Enhancer Permit
    [22] = "infusion_enhancer_permit", -- Infusion Enhancer Permit
    [23] = "freedom_enhancer_permit", -- Freedom Enhancer Permit
    [24] = "heart_enhancer_permit", -- Heart Enhancer Permit
    [25] = "stone_creation", -- Stone of Creation
    [26] = "rock_remembrance", -- Rock of Remembrance
    [27] = "stone_intention", -- Stone of Intention
    [28] = "pearl_dreams", -- Pearl of Dreams
    [29] = "jonny_b_missiles", -- Jonny B. Missiles
    [30] = "anxiety_shock", -- Anxiety Shock
    [31] = "memories_shaft", -- Memories Shaft
    [32] = "logic_blast", -- Logic Blast
    [33] = "skin_knitter", -- Skin Knitter
    [34] = "paint_platform", -- Paint Platform
    [35] = "music_platform", -- Music Platform
    [36] = "free_nara", -- FreeNara
    [37] = "arrow_freedom", -- Arrow of Freedom
    [38] = "map", -- Map
    [39] = "bracers_patient", -- Bracers of the Patient
    [40] = "salts_awareness", -- Salt's Awareness
    [41] = "dandara_arrow_damage_upgrade", -- Dandara Arrow Damage Upgrade
    [42] = "dandara_weapon_damage_upgrade", -- Dandara Weapon Damage Upgrade
    [43] = "salts_awareness_upgrade", -- Salt's Awareness Upgrade
    [44] = "pleas_salt_fear", -- Pleas of the Salt Fear
    [45] = "pleas_salt", -- Pleas of the Salt
    [46] = "salt", -- Salt
}

-- Internal event item names used by the APWorld logic. These are not normal received AP items.
AP_EVENT_ITEM_MAP = {
    ["FinalBoss_Kill"] = "event_kill_eldar",
    ["DLCF_FearEnded"] = "event_true_ending",
    ["D_DLCF_MastersIntroduction"] = "event_masters_introduction",
    ["D_DLCF_ExplorerStart"] = "event_master_explorer_introduction",
    ["D_DLCF_NobleStart"] = "event_master_noble_introduction",
    ["D_DLCF_PersistentStart"] = "event_master_persistent_introduction",
    ["D_DLCF_ExplorerFinish"] = "event_master_explorer_completed",
    ["DLCF_TimeFlagTrap"] = "event_master_persistent_flag",
    ["D_DLCF_NobleFinish"] = "event_master_noble_completed",
    ["D_DLCF_PersistentFinish"] = "event_master_persistent_completed",
    ["DLCF_FreedNara"] = "event_talk_to_nara",
}

-- Hidden rule providers for shop chains. A code is active when that buy check is cleared.
AP_SHOP_CHAIN_MAP = {
    ["Buy Upgrade 1"] = { ref = "@Shop/Buy Upgrade 1/Buy Upgrade 1", code = "buy_upgrade_1_checked" },
    ["Buy Upgrade 2"] = { ref = "@Shop/Buy Upgrade 2/Buy Upgrade 2", code = "buy_upgrade_2_checked" },
    ["Buy Upgrade 3"] = { ref = "@Shop/Buy Upgrade 3/Buy Upgrade 3", code = "buy_upgrade_3_checked" },
    ["Buy Upgrade 4"] = { ref = "@Shop/Buy Upgrade 4/Buy Upgrade 4", code = "buy_upgrade_4_checked" },
    ["Buy Upgrade 5"] = { ref = "@Shop/Buy Upgrade 5/Buy Upgrade 5", code = "buy_upgrade_5_checked" },
    ["Buy Upgrade 6"] = { ref = "@Shop/Buy Upgrade 6/Buy Upgrade 6", code = "buy_upgrade_6_checked" },
    ["Buy Upgrade 7"] = { ref = "@Shop/Buy Upgrade 7/Buy Upgrade 7", code = "buy_upgrade_7_checked" },
    ["Buy Upgrade 8"] = { ref = "@Shop/Buy Upgrade 8/Buy Upgrade 8", code = "buy_upgrade_8_checked" },
    ["Buy Upgrade 9"] = { ref = "@Shop/Buy Upgrade 9/Buy Upgrade 9", code = "buy_upgrade_9_checked" },
    ["Buy Upgrade 10"] = { ref = "@Shop/Buy Upgrade 10/Buy Upgrade 10", code = "buy_upgrade_10_checked" },
    ["Buy Upgrade 11"] = { ref = "@Shop/Buy Upgrade 11/Buy Upgrade 11", code = "buy_upgrade_11_checked" },
    ["Buy Upgrade 12"] = { ref = "@Shop/Buy Upgrade 12/Buy Upgrade 12", code = "buy_upgrade_12_checked" },
    ["Buy Upgrade 13"] = { ref = "@Shop/Buy Upgrade 13/Buy Upgrade 13", code = "buy_upgrade_13_checked" },
    ["Buy Upgrade 14"] = { ref = "@Shop/Buy Upgrade 14/Buy Upgrade 14", code = "buy_upgrade_14_checked" },
    ["Buy Upgrade 15"] = { ref = "@Shop/Buy Upgrade 15/Buy Upgrade 15", code = "buy_upgrade_15_checked" },
    ["Buy Upgrade 16"] = { ref = "@Shop/Buy Upgrade 16/Buy Upgrade 16", code = "buy_upgrade_16_checked" },
    ["Buy Upgrade 17"] = { ref = "@Shop/Buy Upgrade 17/Buy Upgrade 17", code = "buy_upgrade_17_checked" },
    ["Buy Upgrade 18"] = { ref = "@Mana Shop/Buy Upgrade 18/Buy Upgrade 18", code = "buy_upgrade_18_checked" },
    ["Buy Upgrade 19"] = { ref = "@Mana Shop/Buy Upgrade 19/Buy Upgrade 19", code = "buy_upgrade_19_checked" },
    ["Buy Upgrade 20"] = { ref = "@Mana Shop/Buy Upgrade 20/Buy Upgrade 20", code = "buy_upgrade_20_checked" },
    ["Buy Upgrade 21"] = { ref = "@Mana Shop/Buy Upgrade 21/Buy Upgrade 21", code = "buy_upgrade_21_checked" },
    ["Buy Upgrade 22"] = { ref = "@Mana Shop/Buy Upgrade 22/Buy Upgrade 22", code = "buy_upgrade_22_checked" },
    ["Buy Upgrade 23"] = { ref = "@Mana Shop/Buy Upgrade 23/Buy Upgrade 23", code = "buy_upgrade_23_checked" },
    ["Buy Upgrade 24"] = { ref = "@Mana Shop/Buy Upgrade 24/Buy Upgrade 24", code = "buy_upgrade_24_checked" },
    ["Buy Upgrade 25"] = { ref = "@Mana Shop/Buy Upgrade 25/Buy Upgrade 25", code = "buy_upgrade_25_checked" },
    ["Buy Upgrade 26"] = { ref = "@Mana Shop/Buy Upgrade 26/Buy Upgrade 26", code = "buy_upgrade_26_checked" },
    ["Buy Upgrade 27"] = { ref = "@Mana Shop/Buy Upgrade 27/Buy Upgrade 27", code = "buy_upgrade_27_checked" },
    ["Buy Upgrade 28"] = { ref = "@Health Flask Shop/Buy Upgrade 28/Buy Upgrade 28", code = "buy_upgrade_28_checked" },
    ["Buy Upgrade 29"] = { ref = "@Health Flask Shop/Buy Upgrade 29/Buy Upgrade 29", code = "buy_upgrade_29_checked" },
    ["Buy Upgrade 30"] = { ref = "@Health Flask Shop/Buy Upgrade 30/Buy Upgrade 30", code = "buy_upgrade_30_checked" },
    ["Buy Upgrade 31"] = { ref = "@Health Flask Shop/Buy Upgrade 31/Buy Upgrade 31", code = "buy_upgrade_31_checked" },
    ["Buy Upgrade 32"] = { ref = "@Health Flask Shop/Buy Upgrade 32/Buy Upgrade 32", code = "buy_upgrade_32_checked" },
    ["Buy Upgrade 33"] = { ref = "@Health Flask Shop/Buy Upgrade 33/Buy Upgrade 33", code = "buy_upgrade_33_checked" },
    ["Buy Upgrade 34"] = { ref = "@Health Flask Shop/Buy Upgrade 34/Buy Upgrade 34", code = "buy_upgrade_34_checked" },
    ["Buy Upgrade 35"] = { ref = "@Mana Flask Shop/Buy Upgrade 35/Buy Upgrade 35", code = "buy_upgrade_35_checked" },
    ["Buy Upgrade 36"] = { ref = "@Mana Flask Shop/Buy Upgrade 36/Buy Upgrade 36", code = "buy_upgrade_36_checked" },
    ["Buy Upgrade 37"] = { ref = "@Mana Flask Shop/Buy Upgrade 37/Buy Upgrade 37", code = "buy_upgrade_37_checked" },
    ["Buy Upgrade 38"] = { ref = "@Mana Flask Shop/Buy Upgrade 38/Buy Upgrade 38", code = "buy_upgrade_38_checked" },
    ["Buy Upgrade 39"] = { ref = "@Mana Flask Shop/Buy Upgrade 39/Buy Upgrade 39", code = "buy_upgrade_39_checked" },
    ["Buy Upgrade 40"] = { ref = "@Mana Flask Shop/Buy Upgrade 40/Buy Upgrade 40", code = "buy_upgrade_40_checked" },
    ["Buy Upgrade 41"] = { ref = "@Mana Flask Shop/Buy Upgrade 41/Buy Upgrade 41", code = "buy_upgrade_41_checked" },
    ["Buy Upgrade 42"] = { ref = "@Mana Flask Shop/Buy Upgrade 42/Buy Upgrade 42", code = "buy_upgrade_42_checked" },
    ["Buy Upgrade 43"] = { ref = "@Mana Flask Shop/Buy Upgrade 43/Buy Upgrade 43", code = "buy_upgrade_43_checked" },
    ["Buy Upgrade 44"] = { ref = "@Mana Flask Shop/Buy Upgrade 44/Buy Upgrade 44", code = "buy_upgrade_44_checked" },
}

-- Location sections are native PopTracker @Region/Room/Check references.
-- The code field is a readable helper alias for development and debugging.
AP_LOCATION_MAP = {
    ["Missile Alter"] = { code = "loc_missile_alter", ref = "@Village of Artists/Missile Alter/Missile Alter" },
    ["The Village Center (1 Chest)"] = { code = "loc_the_village_center_1_chest", ref = "@Village of Artists/The Village Center/The Village Center (1 Chest)" },
    ["Tarsila's House (1 NPC)"] = { code = "loc_tarsilas_house_1_npc", ref = "@Village of Artists/Tarsila's House/Tarsila's House (1 NPC)" },
    ["Tarsila's House (10 Chest)"] = { code = "loc_tarsilas_house_10_chest", ref = "@Village of Artists/Tarsila's House/Tarsila's House (10 Chest)" },
    ["Beautiful Horizon Avenue (11 Chest)"] = { code = "loc_beautiful_horizon_avenue_11_chest", ref = "@Village of Artists/Beautiful Horizon Avenue/Beautiful Horizon Avenue (11 Chest)" },
    ["Buritis (13 Chest)"] = { code = "loc_buritis_13_chest", ref = "@Village of Artists/Buritis/Buritis (13 Chest)" },
    ["Garantido's Bar (12 Chest)"] = { code = "loc_garantidos_bar_12_chest", ref = "@Village of Artists/Garantido's Bar/Garantido's Bar (12 Chest)" },
    ["Dona Clara's Restaurant (14 Chest)"] = { code = "loc_dona_claras_restaurant_14_chest", ref = "@Village of Artists/Dona Clara's Restaurant/Dona Clara's Restaurant (14 Chest)" },
    ["Lazúli's House (15 Chest)"] = { code = "loc_laz_lis_house_15_chest", ref = "@Village of Artists/Lazúli's House/Lazúli's House (15 Chest)" },
    ["Lazúli's House (16 Chest)"] = { code = "loc_laz_lis_house_16_chest", ref = "@Village of Artists/Lazúli's House/Lazúli's House (16 Chest)" },
    ["Temple of Creation (17 Chest)"] = { code = "loc_temple_of_creation_17_chest", ref = "@Village of Artists/Temple of Creation/Temple of Creation (17 Chest)" },
    ["Temple of Creation (18 Chest)"] = { code = "loc_temple_of_creation_18_chest", ref = "@Village of Artists/Temple of Creation/Temple of Creation (18 Chest)" },
    ["Limits of Sanity (19 Chest)"] = { code = "loc_limits_of_sanity_19_chest", ref = "@Primal Woods/Limits of Sanity/Limits of Sanity (19 Chest)" },
    ["Remembrance Cliff (2 Altar)"] = { code = "loc_remembrance_cliff_2_altar", ref = "@Remembrance Desert/Remembrance Cliff/Remembrance Cliff (2 Altar)" },
    ["Palmares Track (2 Chest)"] = { code = "loc_palmares_track_2_chest", ref = "@Crib of Creation/Palmares Track/Palmares Track (2 Chest)" },
    ["Thommaz's House (2 NPC)"] = { code = "loc_thommazs_house_2_npc", ref = "@Village of Artists/Thommaz's House/Thommaz's House (2 NPC)" },
    ["Eldarian Gates (20 Chest)"] = { code = "loc_eldarian_gates_20_chest", ref = "@Golden Fortress/Eldarian Gates/Eldarian Gates (20 Chest)" },
    ["Wealth Lair (21 Chest)"] = { code = "loc_wealth_lair_21_chest", ref = "@The Colossal Bridge/Wealth Lair/Wealth Lair (21 Chest)" },
    ["Museum Main Hall (22 Chest)"] = { code = "loc_museum_main_hall_22_chest", ref = "@Remembrance Desert/Museum Main Hall/Museum Main Hall (22 Chest)" },
    ["Main Warehouse (23 Chest)"] = { code = "loc_main_warehouse_23_chest", ref = "@Remembrance Desert/Main Warehouse/Main Warehouse (23 Chest)" },
    ["Main Warehouse (24 Chest)"] = { code = "loc_main_warehouse_24_chest", ref = "@Remembrance Desert/Main Warehouse/Main Warehouse (24 Chest)" },
    ["Main Warehouse (25 Chest)"] = { code = "loc_main_warehouse_25_chest", ref = "@Remembrance Desert/Main Warehouse/Main Warehouse (25 Chest)" },
    ["Auditorium (26 Chest)"] = { code = "loc_auditorium_26_chest", ref = "@Remembrance Desert/Auditorium/Auditorium (26 Chest)" },
    ["Overburden Deposits (27 Chest)"] = { code = "loc_overburden_deposits_27_chest", ref = "@Remembrance Desert/Overburden Deposits/Overburden Deposits (27 Chest)" },
    ["The Treasure (28 Chest)"] = { code = "loc_the_treasure_28_chest", ref = "@Remembrance Desert/The Treasure/The Treasure (28 Chest)" },
    ["Foyer of Formidable Burdens (29 Chest)"] = { code = "loc_foyer_of_formidable_burdens_29_chest", ref = "@Remembrance Desert/Foyer of Formidable Burdens/Foyer of Formidable Burdens (29 Chest)" },
    ["Quarter of a Distant Love (3 Altar)"] = { code = "loc_quarter_of_a_distant_love_3_altar", ref = "@Remembrance Desert/Quarter of a Distant Love/Quarter of a Distant Love (3 Altar)" },
    ["Pleasure Woods (3 Chest)"] = { code = "loc_pleasure_woods_3_chest", ref = "@Crib of Creation/Pleasure Woods/Pleasure Woods (3 Chest)" },
    ["Temple of Creation (3 NPC)"] = { code = "loc_temple_of_creation_3_npc", ref = "@Village of Artists/Temple of Creation NPC/Temple of Creation (3 NPC)", mirror = "overworld_npc_check_3" },
    ["Foyer of Formidable Burdens (30 Chest)"] = { code = "loc_foyer_of_formidable_burdens_30_chest", ref = "@Remembrance Desert/Foyer of Formidable Burdens/Foyer of Formidable Burdens (30 Chest)" },
    ["Broken Heart Archive (31 Chest)"] = { code = "loc_broken_heart_archive_31_chest", ref = "@Remembrance Desert/Broken Heart Archive/Broken Heart Archive (31 Chest)" },
    ["Archive of the Child (32 Chest)"] = { code = "loc_archive_of_the_child_32_chest", ref = "@Remembrance Desert/Archive of the Child/Archive of the Child (32 Chest)" },
    ["Overcast Gate Ruins (33 Chest)"] = { code = "loc_overcast_gate_ruins_33_chest", ref = "@Remembrance Desert/Overcast Gate Ruins/Overcast Gate Ruins (33 Chest)" },
    ["Overcast Gate Ruins (34 Chest)"] = { code = "loc_overcast_gate_ruins_34_chest", ref = "@Remembrance Desert/Overcast Gate Ruins/Overcast Gate Ruins (34 Chest)" },
    ["Overcast Gate Ruins (35 Chest)"] = { code = "loc_overcast_gate_ruins_35_chest", ref = "@Remembrance Desert/Overcast Gate Ruins/Overcast Gate Ruins (35 Chest)" },
    ["Structural Cave (36 Chest)"] = { code = "loc_structural_cave_36_chest", ref = "@Intention Capital/Structural Cave/Structural Cave (36 Chest)" },
    ["Side Turn (37 Chest)"] = { code = "loc_side_turn_37_chest", ref = "@Intention Capital/Side Turn/Side Turn (37 Chest)" },
    ["Side Turn (38 Chest)"] = { code = "loc_side_turn_38_chest", ref = "@Intention Capital/Side Turn/Side Turn (38 Chest)" },
    ["Back Alley (39 Chest)"] = { code = "loc_back_alley_39_chest", ref = "@Intention Capital/Back Alley/Back Alley (39 Chest)" },
    ["Crib of Intention (4 Altar)"] = { code = "loc_crib_of_intention_4_altar", ref = "@Intention Capital/Crib of Intention/Crib of Intention (4 Altar)" },
    ["Pleasure Woods (4 Chest)"] = { code = "loc_pleasure_woods_4_chest", ref = "@Crib of Creation/Pleasure Woods/Pleasure Woods (4 Chest)" },
    ["Back Alley (40 Chest)"] = { code = "loc_back_alley_40_chest", ref = "@Intention Capital/Back Alley/Back Alley (40 Chest)" },
    ["Recycle Room (41 Chest)"] = { code = "loc_recycle_room_41_chest", ref = "@Intention Capital/Recycle Room/Recycle Room (41 Chest)" },
    ["The Golden Angle (42 Chest)"] = { code = "loc_the_golden_angle_42_chest", ref = "@Intention Capital/The Golden Angle/The Golden Angle (42 Chest)" },
    ["The Golden Angle (43 Chest)"] = { code = "loc_the_golden_angle_43_chest", ref = "@Intention Capital/The Golden Angle/The Golden Angle (43 Chest)" },
    ["Reasoning Lock (44 Chest)"] = { code = "loc_reasoning_lock_44_chest", ref = "@Intention Capital/Reasoning Lock/Reasoning Lock (44 Chest)" },
    ["Parlance Road (45 Chest)"] = { code = "loc_parlance_road_45_chest", ref = "@Intention Capital/Parlance Road/Parlance Road (45 Chest)" },
    ["The Golden Storage (46 Chest)"] = { code = "loc_the_golden_storage_46_chest", ref = "@Intention Capital/The Golden Storage/The Golden Storage (46 Chest)" },
    ["The Golden Storage (47 Chest)"] = { code = "loc_the_golden_storage_47_chest", ref = "@Intention Capital/The Golden Storage/The Golden Storage (47 Chest)" },
    ["The Golden Storage (48 Chest)"] = { code = "loc_the_golden_storage_48_chest", ref = "@Intention Capital/The Golden Storage/The Golden Storage (48 Chest)" },
    ["The Golden Storage (49 Chest)"] = { code = "loc_the_golden_storage_49_chest", ref = "@Intention Capital/The Golden Storage/The Golden Storage (49 Chest)" },
    ["A Good Bargain (70 Chest)"] = { code = "loc_a_good_bargain_70_chest", ref = "@Intention Capital/A Good Bargain/A Good Bargain (70 Chest)" },
    ["Dream Lands (5 Altar)"] = { code = "loc_dream_lands_5_altar", ref = "@Dream Lands/Dream Lands/Dream Lands (5 Altar)" },
    ["Pleasure Woods (5 Chest)"] = { code = "loc_pleasure_woods_5_chest", ref = "@Crib of Creation/Pleasure Woods/Pleasure Woods (5 Chest)" },
    ["Cave of Desire (51 Chest)"] = { code = "loc_cave_of_desire_51_chest", ref = "@Primal Woods/Cave of Desire/Cave of Desire (51 Chest)" },
    ["Corner's Club (52 Chest)"] = { code = "loc_corners_club_52_chest", ref = "@Dream Lands/Corner's Club/Corner's Club (52 Chest)" },
    ["Dream Lands (53 Chest)"] = { code = "loc_dream_lands_53_chest", ref = "@Dream Lands/Dream Lands/Dream Lands (53 Chest)" },
    ["Dream Lands (55 Chest)"] = { code = "loc_dream_lands_55_chest", ref = "@Dream Lands/Dream Lands/Dream Lands (55 Chest)" },
    ["Dream Lands (56 Chest)"] = { code = "loc_dream_lands_56_chest", ref = "@Dream Lands/Dream Lands/Dream Lands (56 Chest)" },
    ["Dream Lands (57 Chest)"] = { code = "loc_dream_lands_57_chest", ref = "@Dream Lands/Dream Lands/Dream Lands (57 Chest)" },
    ["Dream Lands (58 Chest)"] = { code = "loc_dream_lands_58_chest", ref = "@Dream Lands/Dream Lands/Dream Lands (58 Chest)" },
    ["Dream Lands (59 Chest)"] = { code = "loc_dream_lands_59_chest", ref = "@Dream Lands/Dream Lands/Dream Lands (59 Chest)" },
    ["The Perfect Corner (6 Altar)"] = { code = "loc_the_perfect_corner_6_altar", ref = "@Intention Capital/The Perfect Corner/The Perfect Corner (6 Altar)" },
    ["Confusion Ruins (6 Chest)"] = { code = "loc_confusion_ruins_6_chest", ref = "@Primal Woods/Confusion Ruins/Confusion Ruins (6 Chest)" },
    ["Dream Lands (60 Chest)"] = { code = "loc_dream_lands_60_chest", ref = "@Dream Lands/Dream Lands/Dream Lands (60 Chest)" },
    ["Eagle Highway (61 Chest)"] = { code = "loc_eagle_highway_61_chest", ref = "@Intention Capital/Eagle Highway/Eagle Highway (61 Chest)" },
    ["No Pain, No Gain (62 Chest)"] = { code = "loc_no_pain_no_gain_62_chest", ref = "@Golden Fortress/No Pain, No Gain/No Pain, No Gain (62 Chest)" },
    ["Command Center (63 Chest)"] = { code = "loc_command_center_63_chest", ref = "@Golden Fortress/Command Center/Command Center (63 Chest)" },
    ["Greediness Space (64 Chest)"] = { code = "loc_greediness_space_64_chest", ref = "@Golden Fortress/Greediness Space/Greediness Space (64 Chest)" },
    ["Greediness Space (65 Chest)"] = { code = "loc_greediness_space_65_chest", ref = "@Golden Fortress/Greediness Space/Greediness Space (65 Chest)" },
    ["The Golden Corner (66 Chest)"] = { code = "loc_the_golden_corner_66_chest", ref = "@Intention Capital/The Golden Corner/The Golden Corner (66 Chest)" },
    ["Miserliness Space (67 Chest)"] = { code = "loc_miserliness_space_67_chest", ref = "@Golden Fortress/Miserliness Space/Miserliness Space (67 Chest)" },
    ["Miserliness Space (68 Chest)"] = { code = "loc_miserliness_space_68_chest", ref = "@Golden Fortress/Miserliness Space/Miserliness Space (68 Chest)" },
    ["Miserliness Space (69 Chest)"] = { code = "loc_miserliness_space_69_chest", ref = "@Golden Fortress/Miserliness Space/Miserliness Space (69 Chest)" },
    ["Shock Alter"] = { code = "loc_shock_alter", ref = "@Dream Lands/Corner's Club/Shock Alter" },
    ["Confusion Ruins (7 Chest)"] = { code = "loc_confusion_ruins_7_chest", ref = "@Primal Woods/Confusion Ruins/Confusion Ruins (7 Chest)" },
    ["Paint Well (8 Chest)"] = { code = "loc_paint_well_8_chest", ref = "@Village of Artists/Paint Well/Paint Well (8 Chest)" },
    ["Community Street (9 Chest)"] = { code = "loc_community_street_9_chest", ref = "@Village of Artists/Community Street/Community Street (9 Chest)" },
    ["Overcast Gate Ruins (NPC 4)"] = { code = "loc_overcast_gate_ruins_npc_4", ref = "@Remembrance Desert/Overcast Gate Ruins (NPC 4)/Overcast Gate Ruins (NPC 4)" },
    ["Kill Boss 1"] = { code = "loc_kill_boss_1", ref = "@Village of Artists/Kill Boss 1/Kill Boss 1" },
    ["Kill Boss 2"] = { code = "loc_kill_boss_2", ref = "@Remembrance Desert/Kill Boss 2/Kill Boss 2" },
    ["Kill Eldar"] = { code = "loc_kill_eldar", ref = "@Golden Fortress/Kill Eldar/Kill Eldar" },
    ["Crumbling Hollow (1 Chest)"] = { code = "loc_crumbling_hollow_1_chest", ref = "@Hidden Realms/Crumbling Hollow/Crumbling Hollow (1 Chest)" },
    ["Incident Square (10 Chest)"] = { code = "loc_incident_square_10_chest", ref = "@Hidden Realms/Incident Square/Incident Square (10 Chest)" },
    ["Station Rendezvous (11 Chest)"] = { code = "loc_station_rendezvous_11_chest", ref = "@Ephemeral Station/Station Rendezvous/Station Rendezvous (11 Chest)" },
    ["Station Rendezvous (12 Chest)"] = { code = "loc_station_rendezvous_12_chest", ref = "@Ephemeral Station/Station Rendezvous/Station Rendezvous (12 Chest)" },
    ["Pusher's Assignment (13 Chest)"] = { code = "loc_pushers_assignment_13_chest", ref = "@Ephemeral Station/Pusher's Assignment/Pusher's Assignment (13 Chest)" },
    ["Waiter's Room (14 Chest)"] = { code = "loc_waiters_room_14_chest", ref = "@Ephemeral Station/Waiter's Room/Waiter's Room (14 Chest)" },
    ["Through The Eyes of Fear (15 Chest)"] = { code = "loc_through_the_eyes_of_fear_15_chest", ref = "@Hidden Realms/Through The Eyes of Fear/Through The Eyes of Fear (15 Chest)" },
    ["Hidden Eye (16 Chest)"] = { code = "loc_hidden_eye_16_chest", ref = "@Hidden Realms/Hidden Eye/Hidden Eye (16 Chest)" },
    ["Alchemist's Gallery (17 Chest)"] = { code = "loc_alchemists_gallery_17_chest", ref = "@The Privileged Keep/Alchemist's Gallery/Alchemist's Gallery (17 Chest)" },
    ["Underlying Truth (18 Chest)"] = { code = "loc_underlying_truth_18_chest", ref = "@Hidden Realms/Underlying Truth/Underlying Truth (18 Chest)" },
    ["True Explorers Treasure (19 Chest)"] = { code = "loc_true_explorers_treasure_19_chest", ref = "@Hidden Realms/True Explorers Treasure/True Explorers Treasure (19 Chest)" },
    ["A Dark Angle (2 Chest)"] = { code = "loc_a_dark_angle_2_chest", ref = "@Hidden Realms/A Dark Angle/A Dark Angle (2 Chest)" },
    ["Friendly Gathering (20 Chest)"] = { code = "loc_friendly_gathering_20_chest", ref = "@The Masquerade Ball/Friendly Gathering/Friendly Gathering (20 Chest)" },
    ["Friendly Gathering (21 Chest)"] = { code = "loc_friendly_gathering_21_chest", ref = "@The Masquerade Ball/Friendly Gathering/Friendly Gathering (21 Chest)" },
    ["Ostentation Room (22 Chest)"] = { code = "loc_ostentation_room_22_chest", ref = "@The Masquerade Ball/Ostentation Room/Ostentation Room (22 Chest)" },
    ["Weak-Minded Segregation (23 Chest)"] = { code = "loc_weak_minded_segregation_23_chest", ref = "@The Masquerade Ball/Weak-Minded Segregation/Weak-Minded Segregation (23 Chest)" },
    ["Secrets Beneath Masks (24 Chest)"] = { code = "loc_secrets_beneath_masks_24_chest", ref = "@The Masquerade Ball/Secrets Beneath Masks/Secrets Beneath Masks (24 Chest)" },
    ["Finite Run (3 Chest)"] = { code = "loc_finite_run_3_chest", ref = "@Hidden Realms/Finite Run/Finite Run (3 Chest)" },
    ["Students Way (4 Chest)"] = { code = "loc_students_way_4_chest", ref = "@Hidden Realms/Students Way/Students Way (4 Chest)" },
    ["Pain Sanctuary (5 Chest)"] = { code = "loc_pain_sanctuary_5_chest", ref = "@The Enduring Fortress/Pain Sanctuary/Pain Sanctuary (5 Chest)" },
    ["Wrecked Nakaturen Bridge (6 Chest)"] = { code = "loc_wrecked_nakaturen_bridge_6_chest", ref = "@The Pioneer Facility/Wrecked Nakaturen Bridge/Wrecked Nakaturen Bridge (6 Chest)" },
    ["Nevermore a Beautiful Horizon (7 Chest)"] = { code = "loc_nevermore_a_beautiful_horizon_7_chest", ref = "@Hidden Realms/Nevermore a Beautiful Horizon/Nevermore a Beautiful Horizon (7 Chest)" },
    ["Auditorium Hall (8 Chest)"] = { code = "loc_auditorium_hall_8_chest", ref = "@Masters' Auditorium/Auditorium Hall/Auditorium Hall (8 Chest)" },
    ["Windy Hall (9 Chest)"] = { code = "loc_windy_hall_9_chest", ref = "@Hidden Realms/Windy Hall/Windy Hall (9 Chest)" },
    ["Resilience Growth (3 Altar)"] = { code = "loc_resilience_growth_3_altar", ref = "@Hidden Realms/Resilience Growth/Resilience Growth (3 Altar)" },
    ["Future Path Gate (2 Altar)"] = { code = "loc_future_path_gate_2_altar", ref = "@Ephemeral Station/Future Path Gate/Future Path Gate (2 Altar)" },
    ["The Grand Stage (1 Altar)"] = { code = "loc_the_grand_stage_1_altar", ref = "@Masters' Auditorium/The Grand Stage/The Grand Stage (1 Altar)" },
    ["The Grand Stage (NPC 1)"] = { code = "loc_the_grand_stage_npc_1", ref = "@Masters' Auditorium/The Grand Stage/The Grand Stage (NPC 1)" },
    ["The Grand Stage (NPC 2)"] = { code = "loc_the_grand_stage_npc_2", ref = "@Masters' Auditorium/The Grand Stage/The Grand Stage (NPC 2)" },
    ["The Grand Stage (NPC 3)"] = { code = "loc_the_grand_stage_npc_3", ref = "@Masters' Auditorium/The Grand Stage/The Grand Stage (NPC 3)" },
    ["The Grand Stage (NPC 4)"] = { code = "loc_the_grand_stage_npc_4", ref = "@Masters' Auditorium/The Grand Stage/The Grand Stage (NPC 4)" },
    ["Nakaturen Frigate Elevator (NPC 5)"] = { code = "loc_nakaturen_frigate_elevator_npc_5", ref = "@The Pioneer Facility/Nakaturen Frigate Elevator/Nakaturen Frigate Elevator (NPC 5)" },
    ["Castle Entrance (NPC 6)"] = { code = "loc_castle_entrance_npc_6", ref = "@The Privileged Keep/Castle Entrance/Castle Entrance (NPC 6)" },
    ["Rock Cave (NPC 7)"] = { code = "loc_rock_cave_npc_7", ref = "@The Enduring Fortress/Rock Cave/Rock Cave (NPC 7)" },
    ["Wrecked Nakaturen Bridge (NPC 8)"] = { code = "loc_wrecked_nakaturen_bridge_npc_8", ref = "@The Pioneer Facility/Wrecked Nakaturen Bridge/Wrecked Nakaturen Bridge (NPC 8)" },
    ["Pain Sanctuary (NPC 9)"] = { code = "loc_pain_sanctuary_npc_9", ref = "@The Enduring Fortress/Pain Sanctuary/Pain Sanctuary (NPC 9)" },
    ["Rest of the Acolyte (NPC 10)"] = { code = "loc_rest_of_the_acolyte_npc_10", ref = "@The Privileged Keep/Rest of the Acolyte/Rest of the Acolyte (NPC 10)" },
    ["Rock Cave (NPC 11)"] = { code = "loc_rock_cave_npc_11", ref = "@The Enduring Fortress/Rock Cave/Rock Cave (NPC 11)" },
    ["Nara's Cage (NPC 12)"] = { code = "loc_naras_cage_npc_12", ref = "@Exile of Contemplations/Nara's Cage/Nara's Cage (NPC 12)" },
    -- Current APWorld shop names are generic Buy Upgrade 1..41. Keep old names too for older worlds/tests.
    -- Shop checks use the current APWorld names. Older shop names are kept only as compatibility aliases.
    -- Shop checks use the current APWorld names. Older shop names are kept only as compatibility aliases.
    -- Shop checks use the current APWorld names. Older shop names are kept only as compatibility aliases.
    ["Buy Upgrade 1"] = { code = "loc_buy_upgrade_1", ref = "@Shop/Buy Upgrade 1/Buy Upgrade 1" },
    ["Buy Upgrade 2"] = { code = "loc_buy_upgrade_2", ref = "@Shop/Buy Upgrade 2/Buy Upgrade 2" },
    ["Buy Upgrade 3"] = { code = "loc_buy_upgrade_3", ref = "@Shop/Buy Upgrade 3/Buy Upgrade 3" },
    ["Buy Upgrade 4"] = { code = "loc_buy_upgrade_4", ref = "@Shop/Buy Upgrade 4/Buy Upgrade 4" },
    ["Buy Upgrade 5"] = { code = "loc_buy_upgrade_5", ref = "@Shop/Buy Upgrade 5/Buy Upgrade 5" },
    ["Buy Upgrade 6"] = { code = "loc_buy_upgrade_6", ref = "@Shop/Buy Upgrade 6/Buy Upgrade 6" },
    ["Buy Upgrade 7"] = { code = "loc_buy_upgrade_7", ref = "@Shop/Buy Upgrade 7/Buy Upgrade 7" },
    ["Buy Upgrade 8"] = { code = "loc_buy_upgrade_8", ref = "@Shop/Buy Upgrade 8/Buy Upgrade 8" },
    ["Buy Upgrade 9"] = { code = "loc_buy_upgrade_9", ref = "@Shop/Buy Upgrade 9/Buy Upgrade 9" },
    ["Buy Upgrade 10"] = { code = "loc_buy_upgrade_10", ref = "@Shop/Buy Upgrade 10/Buy Upgrade 10" },
    ["Buy Upgrade 11"] = { code = "loc_buy_upgrade_11", ref = "@Shop/Buy Upgrade 11/Buy Upgrade 11" },
    ["Buy Upgrade 12"] = { code = "loc_buy_upgrade_12", ref = "@Shop/Buy Upgrade 12/Buy Upgrade 12" },
    ["Buy Upgrade 13"] = { code = "loc_buy_upgrade_13", ref = "@Shop/Buy Upgrade 13/Buy Upgrade 13" },
    ["Buy Upgrade 14"] = { code = "loc_buy_upgrade_14", ref = "@Shop/Buy Upgrade 14/Buy Upgrade 14" },
    ["Buy Upgrade 15"] = { code = "loc_buy_upgrade_15", ref = "@Shop/Buy Upgrade 15/Buy Upgrade 15" },
    ["Buy Upgrade 16"] = { code = "loc_buy_upgrade_16", ref = "@Shop/Buy Upgrade 16/Buy Upgrade 16" },
    ["Buy Upgrade 17"] = { code = "loc_buy_upgrade_17", ref = "@Shop/Buy Upgrade 17/Buy Upgrade 17" },
    ["Buy Upgrade 18"] = { code = "loc_buy_upgrade_18", ref = "@Mana Shop/Buy Upgrade 18/Buy Upgrade 18" },
    ["Buy Upgrade 19"] = { code = "loc_buy_upgrade_19", ref = "@Mana Shop/Buy Upgrade 19/Buy Upgrade 19" },
    ["Buy Upgrade 20"] = { code = "loc_buy_upgrade_20", ref = "@Mana Shop/Buy Upgrade 20/Buy Upgrade 20" },
    ["Buy Upgrade 21"] = { code = "loc_buy_upgrade_21", ref = "@Mana Shop/Buy Upgrade 21/Buy Upgrade 21" },
    ["Buy Upgrade 22"] = { code = "loc_buy_upgrade_22", ref = "@Mana Shop/Buy Upgrade 22/Buy Upgrade 22" },
    ["Buy Upgrade 23"] = { code = "loc_buy_upgrade_23", ref = "@Mana Shop/Buy Upgrade 23/Buy Upgrade 23" },
    ["Buy Upgrade 24"] = { code = "loc_buy_upgrade_24", ref = "@Mana Shop/Buy Upgrade 24/Buy Upgrade 24" },
    ["Buy Upgrade 25"] = { code = "loc_buy_upgrade_25", ref = "@Mana Shop/Buy Upgrade 25/Buy Upgrade 25" },
    ["Buy Upgrade 26"] = { code = "loc_buy_upgrade_26", ref = "@Mana Shop/Buy Upgrade 26/Buy Upgrade 26" },
    ["Buy Upgrade 27"] = { code = "loc_buy_upgrade_27", ref = "@Mana Shop/Buy Upgrade 27/Buy Upgrade 27" },
    ["Buy Upgrade 28"] = { code = "loc_buy_upgrade_28", ref = "@Health Flask Shop/Buy Upgrade 28/Buy Upgrade 28" },
    ["Buy Upgrade 29"] = { code = "loc_buy_upgrade_29", ref = "@Health Flask Shop/Buy Upgrade 29/Buy Upgrade 29" },
    ["Buy Upgrade 30"] = { code = "loc_buy_upgrade_30", ref = "@Health Flask Shop/Buy Upgrade 30/Buy Upgrade 30" },
    ["Buy Upgrade 31"] = { code = "loc_buy_upgrade_31", ref = "@Health Flask Shop/Buy Upgrade 31/Buy Upgrade 31" },
    ["Buy Upgrade 32"] = { code = "loc_buy_upgrade_32", ref = "@Health Flask Shop/Buy Upgrade 32/Buy Upgrade 32" },
    ["Buy Upgrade 33"] = { code = "loc_buy_upgrade_33", ref = "@Health Flask Shop/Buy Upgrade 33/Buy Upgrade 33" },
    ["Buy Upgrade 34"] = { code = "loc_buy_upgrade_34", ref = "@Health Flask Shop/Buy Upgrade 34/Buy Upgrade 34" },
    ["Buy Upgrade 35"] = { code = "loc_buy_upgrade_35", ref = "@Mana Flask Shop/Buy Upgrade 35/Buy Upgrade 35" },
    ["Buy Upgrade 36"] = { code = "loc_buy_upgrade_36", ref = "@Mana Flask Shop/Buy Upgrade 36/Buy Upgrade 36" },
    ["Buy Upgrade 37"] = { code = "loc_buy_upgrade_37", ref = "@Mana Flask Shop/Buy Upgrade 37/Buy Upgrade 37" },
    ["Buy Upgrade 38"] = { code = "loc_buy_upgrade_38", ref = "@Mana Flask Shop/Buy Upgrade 38/Buy Upgrade 38" },
    ["Buy Upgrade 39"] = { code = "loc_buy_upgrade_39", ref = "@Mana Flask Shop/Buy Upgrade 39/Buy Upgrade 39" },
    ["Buy Upgrade 40"] = { code = "loc_buy_upgrade_40", ref = "@Mana Flask Shop/Buy Upgrade 40/Buy Upgrade 40" },
    ["Buy Upgrade 41"] = { code = "loc_buy_upgrade_41", ref = "@Mana Flask Shop/Buy Upgrade 41/Buy Upgrade 41" },
    ["Buy Upgrade 42"] = { code = "loc_buy_upgrade_42", ref = "@Mana Flask Shop/Buy Upgrade 42/Buy Upgrade 42" },
    ["Buy Upgrade 43"] = { code = "loc_buy_upgrade_43", ref = "@Mana Flask Shop/Buy Upgrade 43/Buy Upgrade 43" },
    ["Buy Upgrade 44"] = { code = "loc_buy_upgrade_44", ref = "@Mana Flask Shop/Buy Upgrade 44/Buy Upgrade 44" },
    ["Buy Heart Shop Upgrade #1"] = { code = "loc_buy_heart_shop_upgrade_1", ref = "@Shop/Buy Upgrade 1/Buy Upgrade 1" },
    ["Buy Heart Shop Upgrade #2"] = { code = "loc_buy_heart_shop_upgrade_2", ref = "@Shop/Buy Upgrade 2/Buy Upgrade 2" },
    ["Buy Heart Shop Upgrade #3"] = { code = "loc_buy_heart_shop_upgrade_3", ref = "@Shop/Buy Upgrade 3/Buy Upgrade 3" },
    ["Buy Heart Shop Upgrade #4"] = { code = "loc_buy_heart_shop_upgrade_4", ref = "@Shop/Buy Upgrade 4/Buy Upgrade 4" },
    ["Buy Heart Shop Upgrade #5"] = { code = "loc_buy_heart_shop_upgrade_5", ref = "@Shop/Buy Upgrade 5/Buy Upgrade 5" },
    ["Buy Heart Shop Upgrade #6"] = { code = "loc_buy_heart_shop_upgrade_6", ref = "@Shop/Buy Upgrade 6/Buy Upgrade 6" },
    ["Buy Heart Shop Upgrade #7"] = { code = "loc_buy_heart_shop_upgrade_7", ref = "@Shop/Buy Upgrade 7/Buy Upgrade 7" },
    ["Buy Heart Shop Upgrade #8"] = { code = "loc_buy_heart_shop_upgrade_8", ref = "@Shop/Buy Upgrade 8/Buy Upgrade 8" },
    ["Buy Heart Shop Upgrade #9"] = { code = "loc_buy_heart_shop_upgrade_9", ref = "@Shop/Buy Upgrade 9/Buy Upgrade 9" },
    ["Buy Heart Shop Upgrade #10"] = { code = "loc_buy_heart_shop_upgrade_10", ref = "@Shop/Buy Upgrade 10/Buy Upgrade 10" },
    ["Buy Heart Shop Upgrade #11"] = { code = "loc_buy_heart_shop_upgrade_11", ref = "@Shop/Buy Upgrade 11/Buy Upgrade 11" },
    ["Buy Heart Shop Upgrade #12"] = { code = "loc_buy_heart_shop_upgrade_12", ref = "@Shop/Buy Upgrade 12/Buy Upgrade 12" },
    ["Buy Heart Shop Upgrade #13"] = { code = "loc_buy_heart_shop_upgrade_13", ref = "@Shop/Buy Upgrade 13/Buy Upgrade 13" },
    ["Buy Heart Shop Upgrade #14"] = { code = "loc_buy_heart_shop_upgrade_14", ref = "@Shop/Buy Upgrade 14/Buy Upgrade 14" },
    ["Buy Heart Shop Upgrade #15"] = { code = "loc_buy_heart_shop_upgrade_15", ref = "@Shop/Buy Upgrade 15/Buy Upgrade 15" },
    ["Buy Heart Shop Upgrade #16"] = { code = "loc_buy_heart_shop_upgrade_16", ref = "@Shop/Buy Upgrade 16/Buy Upgrade 16" },
    ["Buy Heart Shop Upgrade #17"] = { code = "loc_buy_heart_shop_upgrade_17", ref = "@Shop/Buy Upgrade 17/Buy Upgrade 17" },
    ["Buy Mana Shop Upgrade #1"] = { code = "loc_buy_mana_shop_upgrade_1", ref = "@Mana Shop/Buy Upgrade 18/Buy Upgrade 18" },
    ["Buy Mana Shop Upgrade #2"] = { code = "loc_buy_mana_shop_upgrade_2", ref = "@Mana Shop/Buy Upgrade 19/Buy Upgrade 19" },
    ["Buy Mana Shop Upgrade #3"] = { code = "loc_buy_mana_shop_upgrade_3", ref = "@Mana Shop/Buy Upgrade 20/Buy Upgrade 20" },
    ["Buy Mana Shop Upgrade #4"] = { code = "loc_buy_mana_shop_upgrade_4", ref = "@Mana Shop/Buy Upgrade 21/Buy Upgrade 21" },
    ["Buy Mana Shop Upgrade #5"] = { code = "loc_buy_mana_shop_upgrade_5", ref = "@Mana Shop/Buy Upgrade 22/Buy Upgrade 22" },
    ["Buy Mana Shop Upgrade #6"] = { code = "loc_buy_mana_shop_upgrade_6", ref = "@Mana Shop/Buy Upgrade 23/Buy Upgrade 23" },
    ["Buy Mana Shop Upgrade #7"] = { code = "loc_buy_mana_shop_upgrade_7", ref = "@Mana Shop/Buy Upgrade 24/Buy Upgrade 24" },
    ["Buy Mana Shop Upgrade #8"] = { code = "loc_buy_mana_shop_upgrade_8", ref = "@Mana Shop/Buy Upgrade 25/Buy Upgrade 25" },
    ["Buy Mana Shop Upgrade #9"] = { code = "loc_buy_mana_shop_upgrade_9", ref = "@Mana Shop/Buy Upgrade 26/Buy Upgrade 26" },
    ["Buy Mana Shop Upgrade #10"] = { code = "loc_buy_mana_shop_upgrade_10", ref = "@Mana Shop/Buy Upgrade 27/Buy Upgrade 27" },
    ["Buy Health Flask Shop Upgrade #1"] = { code = "loc_buy_health_flask_shop_upgrade_1", ref = "@Health Flask Shop/Buy Upgrade 28/Buy Upgrade 28" },
    ["Buy Health Flask Shop Upgrade #2"] = { code = "loc_buy_health_flask_shop_upgrade_2", ref = "@Health Flask Shop/Buy Upgrade 29/Buy Upgrade 29" },
    ["Buy Health Flask Shop Upgrade #3"] = { code = "loc_buy_health_flask_shop_upgrade_3", ref = "@Health Flask Shop/Buy Upgrade 30/Buy Upgrade 30" },
    ["Buy Health Flask Shop Upgrade #4"] = { code = "loc_buy_health_flask_shop_upgrade_4", ref = "@Health Flask Shop/Buy Upgrade 31/Buy Upgrade 31" },
    ["Buy Health Flask Shop Upgrade #5"] = { code = "loc_buy_health_flask_shop_upgrade_5", ref = "@Health Flask Shop/Buy Upgrade 32/Buy Upgrade 32" },
    ["Buy Health Flask Shop Upgrade #6"] = { code = "loc_buy_health_flask_shop_upgrade_6", ref = "@Health Flask Shop/Buy Upgrade 33/Buy Upgrade 33" },
    ["Buy Health Flask Shop Upgrade #7"] = { code = "loc_buy_health_flask_shop_upgrade_7", ref = "@Health Flask Shop/Buy Upgrade 34/Buy Upgrade 34" },
    ["Buy Mana Flask Shop Upgrade #1"] = { code = "loc_buy_mana_flask_shop_upgrade_1", ref = "@Mana Flask Shop/Buy Upgrade 35/Buy Upgrade 35" },
    ["Buy Mana Flask Shop Upgrade #2"] = { code = "loc_buy_mana_flask_shop_upgrade_2", ref = "@Mana Flask Shop/Buy Upgrade 36/Buy Upgrade 36" },
    ["Buy Mana Flask Shop Upgrade #3"] = { code = "loc_buy_mana_flask_shop_upgrade_3", ref = "@Mana Flask Shop/Buy Upgrade 37/Buy Upgrade 37" },
    ["Buy Mana Flask Shop Upgrade #4"] = { code = "loc_buy_mana_flask_shop_upgrade_4", ref = "@Mana Flask Shop/Buy Upgrade 38/Buy Upgrade 38" },
    ["Buy Mana Flask Shop Upgrade #5"] = { code = "loc_buy_mana_flask_shop_upgrade_5", ref = "@Mana Flask Shop/Buy Upgrade 39/Buy Upgrade 39" },
    ["Buy Mana Flask Shop Upgrade #6"] = { code = "loc_buy_mana_flask_shop_upgrade_6", ref = "@Mana Flask Shop/Buy Upgrade 40/Buy Upgrade 40" },
    ["Buy Mana Flask Shop Upgrade #7"] = { code = "loc_buy_mana_flask_shop_upgrade_7", ref = "@Mana Flask Shop/Buy Upgrade 41/Buy Upgrade 41" },
    ["Event: Masters Introduction"] = { code = "loc_event_masters_introduction", ref = "@Masters' Auditorium/Masters Introduction/Event: Masters Introduction", event = "event_masters_introduction" },
    ["Event: Master Explorer Introduction"] = { code = "loc_event_master_explorer_introduction", ref = "@The Pioneer Facility/Master Explorer Introduction/Event: Master Explorer Introduction", event = "event_master_explorer_introduction" },
    ["Event: Master Noble Introduction"] = { code = "loc_event_master_noble_introduction", ref = "@The Privileged Keep/Master Noble Introduction/Event: Master Noble Introduction", event = "event_master_noble_introduction" },
    ["Event: Master Persistent Introduction"] = { code = "loc_event_master_persistent_introduction", ref = "@The Enduring Fortress/Master Persistent Introduction/Event: Master Persistent Introduction", event = "event_master_persistent_introduction" },
    ["Event: Master Explorer Completed"] = { code = "loc_event_master_explorer_completed", ref = "@The Pioneer Facility/Master Explorer Completed/Event: Master Explorer Completed", event = "event_master_explorer_completed" },
    ["Event: Master Persistent Flag"] = { code = "loc_event_master_persistent_flag", ref = "@The Enduring Fortress/Master Persistent Flag/Event: Master Persistent Flag", event = "event_master_persistent_flag" },
    ["Event: Master Noble Completed"] = { code = "loc_event_master_noble_completed", ref = "@The Privileged Keep/Master Noble Completed/Event: Master Noble Completed", event = "event_master_noble_completed" },
    ["Event: Master Persistent Completed"] = { code = "loc_event_master_persistent_completed", ref = "@The Enduring Fortress/Master Persistent Completed/Event: Master Persistent Completed", event = "event_master_persistent_completed" },
    ["Event: Kill Eldar"] = { code = "loc_event_kill_eldar", ref = "@Golden Fortress/Kill Eldar/Kill Eldar", event = "event_kill_eldar" },
    ["Event: Talk to Nara"] = { code = "loc_event_talk_to_nara", ref = "@Exile of Contemplations/Talk to Nara/Event: Talk to Nara", event = "event_talk_to_nara" },
    ["Event: Ture Ending"] = { code = "loc_event_ture_ending", ref = "@The Salt Is Hesitant/Ture Ending/Event: Ture Ending", event = "event_true_ending" },
}
